#!/usr/bin/env python3
"""Render a visual smoke comparison markdown report from a runs/<id>/ directory."""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

COMMANDS = [
    ("doctor.json", "doctor"),
    ("provider_capabilities.json", "provider capabilities"),
    ("repo_status.json", "repo status"),
    ("refs_compare.json", "refs compare"),
    ("pr_view.json", "pr view"),
    ("pr_checks.json", "pr checks"),
    ("merge_plan.json", "merge plan"),
]

MCP_COMMANDS = [
    ("doctor.json", "doctor"),
    ("provider_capabilities.json", "provider capabilities"),
    ("repo_status.json", "repo status"),
    ("refs_compare.json", "ref compare"),
    ("pr_status.json", "pr status"),
    ("pr_checks.json", "pr checks"),
    ("merge_plan.json", "merge plan"),
    ("sync_plan.json", "sync plan"),
]

ENVELOPE_KEYS = [
    "type",
    "schema_version",
    "provider_id",
    "remote_name",
    "repo_id",
    "observed_at",
    "ok",
]

COMPARE_KEYS: dict[str, list[str]] = {
    "repo_status.json": ["default_branch", "capabilities"],
    "refs_compare.json": ["base_ref", "head_ref", "ahead_by", "behind_by", "base_sha", "head_sha"],
    "pr_view.json": ["pr_number", "state", "mergeability", "base_ref", "head_ref", "title"],
    "pr_checks.json": ["head_sha", "check_conclusion"],
    "merge_plan.json": ["mergeable", "blockers", "check_conclusion"],
    "provider_capabilities.json": ["auth_envs", "check_sources", "write_support"],
}


def load_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {"ok": False, "type": "invalid_json", "path": str(path)}


def load_mcp_record(path: Path) -> tuple[dict[str, Any] | None, bool | None]:
    raw = load_json(path)
    if raw is None:
        return None, None
    if "packet" in raw:
        return raw.get("packet"), raw.get("isError")
    return raw, None


def mcp_ok_cell(packet: dict[str, Any] | None, is_error: bool | None) -> str:
    if packet is None:
        return "—"
    if is_error and packet.get("ok") is not False:
        return "**fail** (mcp isError)"
    return ok_cell(packet)


def ok_cell(packet: dict[str, Any] | None) -> str:
    if packet is None:
        return "—"
    if packet.get("type") == "smoke_skipped":
        return "skip"
    if packet.get("ok") is True:
        return "pass"
    if packet.get("ok") is False:
        err = packet.get("error") or packet.get("forge_error") or packet.get("code") or "fail"
        if isinstance(err, dict):
            err = err.get("code") or err.get("message") or "fail"
        return f"**fail** ({err})"
    return "?"


def fmt_val(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, (list, dict)):
        text = json.dumps(value, separators=(",", ":"))
        if len(text) > 80:
            text = text[:77] + "..."
        return f"`{text}`"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    return f"`{value}`"


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: render-smoke-report.py <run-dir>", file=sys.stderr)
        return 1

    run_dir = Path(sys.argv[1]).resolve()
    manifest = load_json(run_dir / "manifest.json") or {}
    run_id = manifest.get("run_id", run_dir.name)

    providers = sorted(
        p.name
        for p in run_dir.iterdir()
        if p.is_dir() and ((p / "meta.json").exists() or (p / "skipped.json").exists())
    )
    if not providers:
        providers = sorted(p.name for p in run_dir.iterdir() if p.is_dir())

    packets: dict[str, dict[str, dict[str, Any] | None]] = {}
    mcp_packets: dict[str, dict[str, dict[str, Any] | None]] = {}
    mcp_errors: dict[str, dict[str, bool | None]] = {}
    for provider in providers:
        packets[provider] = {}
        mcp_packets[provider] = {}
        mcp_errors[provider] = {}
        for filename, _ in COMMANDS:
            packets[provider][filename] = load_json(run_dir / provider / filename)
        for filename, _ in MCP_COMMANDS:
            packet, is_error = load_mcp_record(run_dir / provider / "mcp" / filename)
            mcp_packets[provider][filename] = packet
            mcp_errors[provider][filename] = is_error
        if packets[provider].get("doctor.json") is None:
            packets[provider]["doctor.json"] = load_json(run_dir / provider / "skipped.json")

    lines: list[str] = []
    lines.append(f"# Smoke results — `{run_id}`")
    lines.append("")
    lines.append(f"Generated by `scripts/render-smoke-report.py`. Packets live under `runs/{run_id}/`.")
    lines.append("")

    fixture = manifest.get("fixture") or {}
    if fixture:
        lines.append("## Fixture")
        lines.append("")
        lines.append(f"- `main` = `{fixture.get('main', '—')}`")
        lines.append(f"- `feature/smoke-1` = `{fixture.get('feature_smoke_1', '—')}`")
        lines.append(f"- Started at `{manifest.get('started_at', '—')}`")
        lines.append("")

    lines.append("## Battery summary")
    lines.append("")
    header = "| Command | " + " | ".join(providers) + " |"
    sep = "|---|" + "|".join(["---"] * len(providers)) + "|"
    lines.append(header)
    lines.append(sep)
    for filename, label in COMMANDS:
        row = [label] + [ok_cell(packets[p].get(filename)) for p in providers]
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    has_mcp = any((run_dir / p / "mcp").is_dir() for p in providers)
    if has_mcp:
        lines.append("## MCP battery summary (remogram-mcp stdio)")
        lines.append("")
        lines.append(header)
        lines.append(sep)
        for filename, label in MCP_COMMANDS:
            row = [
                label,
            ] + [
                mcp_ok_cell(mcp_packets[p].get(filename), mcp_errors[p].get(filename))
                for p in providers
            ]
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    lines.append("## Envelope parity (CLI)")
    lines.append("")
    for filename, label in COMMANDS:
        keys_present = any(packets[p].get(filename) for p in providers)
        if not keys_present:
            continue
        lines.append(f"### {label}")
        lines.append("")
        env_header = "| Field | " + " | ".join(providers) + " |"
        lines.append(env_header)
        lines.append(sep)
        for key in ENVELOPE_KEYS:
            row = [f"`{key}`"] + [
                fmt_val((packets[p].get(filename) or {}).get(key)) for p in providers
            ]
            lines.append("| " + " | ".join(row) + " |")
        extra = COMPARE_KEYS.get(filename, [])
        for key in extra:
            row = [f"`{key}`"] + [
                fmt_val((packets[p].get(filename) or {}).get(key)) for p in providers
            ]
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")

    lines.append("## Full packets (CLI)")
    lines.append("")
    for filename, label in COMMANDS:
        lines.append(f"### {label}")
        lines.append("")
        for provider in providers:
            packet = packets[provider].get(filename)
            lines.append(f"<details>")
            lines.append(f"<summary><code>{provider}</code> — {ok_cell(packet)}</summary>")
            lines.append("")
            lines.append("```json")
            if packet is None:
                lines.append("{}")
            else:
                lines.append(json.dumps(packet, indent=2, sort_keys=True))
            lines.append("```")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    if has_mcp:
        lines.append("## Full MCP packets")
        lines.append("")
        for filename, label in MCP_COMMANDS:
            lines.append(f"### MCP {label}")
            lines.append("")
            for provider in providers:
                packet = mcp_packets[provider].get(filename)
                is_error = mcp_errors[provider].get(filename)
                lines.append("<details>")
                lines.append(
                    f"<summary><code>{provider}</code> — "
                    f"{mcp_ok_cell(packet, is_error)}</summary>"
                )
                lines.append("")
                lines.append("```json")
                if packet is None:
                    lines.append("{}")
                else:
                    lines.append(json.dumps(packet, indent=2, sort_keys=True))
                lines.append("```")
                lines.append("")
                lines.append("</details>")
                lines.append("")

    lines.append("## Links")
    lines.append("")
    lines.append("- GitLab MR: https://gitlab.com/attebury/remogram-smoke/-/merge_requests/1")
    lines.append("- GitHub PR: https://github.com/attebury/remogram-smoke/pull/1")
    lines.append("- Gitea PR: http://localhost:3000/attebury/remogram-smoke/pulls/1")
    lines.append("")

    report = "\n".join(lines)
    (run_dir / "REPORT.md").write_text(report)
    print(f"Wrote {run_dir / 'REPORT.md'} ({len(report)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
